### ISSUE TITLE
Faild to build using Ubuntu 14.04 and 15.10 default cross compilers

### ISSUE THREAD

**Issue by yahoo2016** [CM-Shield/android_kernel_nvidia_foster#1]
The following patch was used to fix build error. 

[code]
diff -crB android_kernel_nvidia_foster-cm-12.1/drivers/iio/light/Makefile cm-12.1/drivers/iio/light/Makefile
*** android_kernel_nvidia_foster-cm-12.1/drivers/iio/light/Makefile	2015-11-23 18:21:32.000000000 -0500
--- cm-12.1/drivers/iio/light/Makefile	2015-12-30 17:38:40.689390595 -0500
***************
*** 4,10 ****
  
  GCOV_PROFILE := y
  
! ccflags-y += -Werror
  obj-$(CONFIG_ADJD_S311)		+= adjd_s311.o
  obj-$(CONFIG_SENSORS_LM3533)	+= lm3533-als.o
  obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
--- 4,10 ----
  
  GCOV_PROFILE := y
  
! #ccflags-y += -Werror
  obj-$(CONFIG_ADJD_S311)		+= adjd_s311.o
  obj-$(CONFIG_SENSORS_LM3533)	+= lm3533-als.o
  obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
diff -crB android_kernel_nvidia_foster-cm-12.1/drivers/platform/tegra/tegra21_clocks.c cm-12.1/drivers/platform/tegra/tegra21_clocks.c
*** android_kernel_nvidia_foster-cm-12.1/drivers/platform/tegra/tegra21_clocks.c	2015-11-23 18:21:32.000000000 -0500
--- cm-12.1/drivers/platform/tegra/tegra21_clocks.c	2015-12-30 17:45:23.992096611 -0500
***************
*** 1061,1067 ****
   */
  static void tegra21_cpu_clk_init(struct clk *c)
  {
! 	c->state = (!is_lp_cluster() == (c->u.cpu.mode == MODE_G)) ? ON : OFF;
  }
  
  static int tegra21_cpu_clk_enable(struct clk *c)
--- 1061,1067 ----
   */
  static void tegra21_cpu_clk_init(struct clk *c)
  {
! 	c->state = ((!is_lp_cluster()) == (c->u.cpu.mode == MODE_G)) ? ON : OFF;
  }
  
  static int tegra21_cpu_clk_enable(struct clk *c)
diff -crB android_kernel_nvidia_foster-cm-12.1/drivers/video/tegra/dc/edid.c cm-12.1/drivers/video/tegra/dc/edid.c
*** android_kernel_nvidia_foster-cm-12.1/drivers/video/tegra/dc/edid.c	2015-11-23 18:21:32.000000000 -0500
--- cm-12.1/drivers/video/tegra/dc/edid.c	2015-12-14 17:13:23.000000000 -0500
***************
*** 598,604 ****
  {
  	int i;
  	int j;
! 	int ret;
  	int extension_blocks;
  	struct tegra_edid_pvt *new_data, *old_data;
  	u8 checksum = 0;
--- 598,604 ----
  {
  	int i;
  	int j;
! 	int ret = 0;
  	int extension_blocks;
  	struct tegra_edid_pvt *new_data, *old_data;
  	u8 checksum = 0;
diff -crB android_kernel_nvidia_foster-cm-12.1/drivers/video/tegra/nvmap/nvmap_init.c cm-12.1/drivers/video/tegra/nvmap/nvmap_init.c
*** android_kernel_nvidia_foster-cm-12.1/drivers/video/tegra/nvmap/nvmap_init.c	2015-11-23 18:21:32.000000000 -0500
--- cm-12.1/drivers/video/tegra/nvmap/nvmap_init.c	2015-12-14 17:17:01.000000000 -0500
***************
*** 216,222 ****
   */
  int nvmap_init(struct platform_device *pdev)
  {
! 	int err;
  	struct dma_declare_info vpr_dma_info;
  	struct dma_declare_info generic_dma_info;
  
--- 216,222 ----
   */
  int nvmap_init(struct platform_device *pdev)
  {
! 	int err = 0;
  	struct dma_declare_info vpr_dma_info;
  	struct dma_declare_info generic_dma_info;
  
[/code]

**Comment by webgeek1234** [comment]
Closing as cleanup since this kernel isn't supported anymore.
